plugins {
    id 'java'
    id 'maven-publish'
}

group = 'link.e4mc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

compileJava {
    sourceCompatibility = 8
    targetCompatibility = 8
}

dependencies {
    implementation("io.netty:netty-all:4.1.130.Final")
}

publishing {
    repositories {
        maven {
            name = "JopgaRepo"
            url = uri("https://repo.jopga.me/releases")

            credentials {
                username = project.findProperty("jopga.user")?.toString()
                password = project.findProperty("jopga.key")?.toString()
            }
        }
    }

    publications {
        maven(MavenPublication) {
            groupId = project.group.toString()
            version = project.version.toString()

            artifact(tasks.named("jar")) {
                classifier = ""
            }
        }
    }
}
